### ISSUE TITLE
something wrong？

### ISSUE THREAD

**Issue by AndrewZheng-AI** [joshsaxe/eXposeDeepNeuralNetwork#2]
I run the code from github
python model_server.py ../data/models/urls/
and get:

Traceback (most recent call last):
  File "model_server.py", line 28, in <module>
    'model_weights.h5',
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2538, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2970, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2148, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 551, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shapes must be equal rank, but are 3 and 4 for 'Assign_1' (op: 'Assign') with input shapes: [2,32,256], [256,32,2,1].

anybody known what happend?

**Comment by AndrewZheng-AI** [comment]
tha whole error is

root@ubuntu:~/eXposeDeepNeuralNetwork/src# python model_server.py ../data/models/urls/
Using TensorFlow backend.
Loading models
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `InputLayer` call to the Keras 2 API: `InputLayer(dtype="int32", batch_input_shape=[None, 100..., name="main_input")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(embeddings_initializer="uniform", trainable=True, name="embedding_1", output_dim=32, activity_regularizer=None, embeddings_regularizer=None, input_dtype="int32", embeddings_constraint=None, mask_zero=False, input_dim=100, batch_input_shape=[None, 100..., input_length=100)`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(trainable=True, filters=256, use_bias=True, bias_regularizer=None, input_dtype="float32", activation="relu", kernel_initializer="uniform", kernel_constraint=None, activity_regularizer=None, input_shape=(None, Non..., padding="same", strides=1, batch_input_shape=[None, 100..., name="convolution1d_1", bias_constraint=None, kernel_regularizer=None, kernel_size=2)`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.5, trainable=True, name="dropout_1")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(trainable=True, filters=256, use_bias=True, bias_regularizer=None, input_dtype="float32", activation="relu", kernel_initializer="uniform", kernel_constraint=None, activity_regularizer=None, input_shape=(None, Non..., padding="same", strides=1, batch_input_shape=[None, 100..., name="convolution1d_2", bias_constraint=None, kernel_regularizer=None, kernel_size=3)`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.5, trainable=True, name="dropout_2")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(trainable=True, filters=256, use_bias=True, bias_regularizer=None, input_dtype="float32", activation="relu", kernel_initializer="uniform", kernel_constraint=None, activity_regularizer=None, input_shape=(None, Non..., padding="same", strides=1, batch_input_shape=[None, 100..., name="convolution1d_3", bias_constraint=None, kernel_regularizer=None, kernel_size=4)`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.5, trainable=True, name="dropout_3")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(trainable=True, filters=256, use_bias=True, bias_regularizer=None, input_dtype="float32", activation="relu", kernel_initializer="uniform", kernel_constraint=None, activity_regularizer=None, input_shape=(None, Non..., padding="same", strides=1, batch_input_shape=[None, 100..., name="convolution1d_4", bias_constraint=None, kernel_regularizer=None, kernel_size=5)`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.5, trainable=True, name="dropout_4")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(name="dense_1", bias_regularizer=None, bias_constraint=None, activity_regularizer=None, trainable=True, kernel_constraint=None, kernel_regularizer=None, input_dim=None, units=1024, kernel_initializer="glorot_uniform", use_bias=True, activation="relu")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.5, trainable=True, name="dropout_5")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(name="dense_2", bias_regularizer=None, bias_constraint=None, activity_regularizer=None, trainable=True, kernel_constraint=None, kernel_regularizer=None, input_dim=None, units=1024, kernel_initializer="glorot_uniform", use_bias=True, activation="relu")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.5, trainable=True, name="dropout_6")`
  return cls(**config)
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:1231: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(name="dense_3", bias_regularizer=None, bias_constraint=None, activity_regularizer=None, trainable=True, kernel_constraint=None, kernel_regularizer=None, input_dim=None, units=1, kernel_initializer="glorot_uniform", use_bias=True, activation="sigmoid")`
  return cls(**config)
Traceback (most recent call last):
  File "model_server.py", line 28, in <module>
    'model_weights.h5',
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2538, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2970, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2148, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 551, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shapes must be equal rank, but are 3 and 4 for 'Assign_1' (op: 'Assign') with input shapes: [2,32,256], [256,32,2,1].

**Comment by zsavvas** [comment]
Same problem here. 

Can you let us know the exact versions of keras and tensorflow that work with this project?
